### PR TITLE
Fix fakeXHR requests in Node.

### LINKED ISSUE #508: Failing tests when running in browsers
The error appearing when running tests from current `master` is: 

```
TypeError: 'undefined' is not a function (evaluating 'sinon.useFakeXMLHttpRequest()')
at Object.sinon.fakeServer.create (http://localhost:8123/lib/sinon/util/fake_server.js:82:30)
```

If my use of `git bisect` is correct, then c28f47f917984167c88e24b04f6aa400654cf749 is the first commit where the tests fail when run in a browser.

**NOTE:** You will need to run the tests from the test page served from a webserver, and not just loaded from the file system, or you will get other errors as well, making it more difficult to isolate this issue.

### LINKED ISSUE #657: JSDom + fakeXHR troubles
Sinon version: **v1.12.2**
Environment: **OSX 10.10.1**
Example URL: **N/A**

**Description**
I'm attempting to write unit tests for jQuery ajax requests in a JSDom environment, but Sinon's fake XHR is not intercepting the requests. The exact same suite **does** work in the browser.

I know the jQueryXHR + JSDom combo can cause some folks trouble, but I'm fairly certain that Ive got them configured correctly. I've set the `global.window` and `global.XMLHttpRequest` object from JSDom so that jQuery can make XHR requests, and I've verified that this works. The issue comes in when I try to fake the requests with Sinon: they aren't intercepted.

It comes down to [`sinonXhr.supportsXHR`](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_xml_http_request.js#L28) being calculated as false. This follows from [this line](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_xml_http_request.js#L25), where it looks for `XMLHttpRequest` on the local variable `global`. That local variable is passed in [here](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/util/fake_xml_http_request.js#L614). In Node, `this` is an empty object, while `global` is where it **should** be looking at for the xml http request.

It seems unlikely to me that this would go unnoticed for so long, so maybe I'm configuring things oddly. Has anyone had success with jQuery+JSDom+Sinon's FakeXHRs?

### PR DESCRIPTION
**Pull request by jmeas**
Sinon was unable to detect XHR support when loaded in certain
Node environments. This was a regression introduced in #515
to resolve #508 and #511.

Resolves #657 

===

Reimplements #659. This one actually seems to work. Refer to that PR for a description on how to test it.

### CODE REVIEW

**Comment by jmeas** [comment]
Test repo [here](https://github.com/jmeas/backbone.simple-auth).

Run `gulp` to run the node unit tests. They will pass.

Run `gulp test:browser` to start up a server for the client-side tests. Navigate to `http://localhost:7777/test/runner.html` to see that they, too, pass.

After you've done that, dig into `package.json` and install the normal version of sinon. The node tests will no longer pass.

**Comment by cjohansen** [comment]
Thanks!

**Comment by jmeas** [comment]
:dancers:

File: lib/sinon/util/fake_xml_http_request.js [hunk 1]
```diff
@@ -611,4 +611,4 @@
         makeApi(sinon);
     }
 
-})(typeof self !== "undefined" ? self : this);
+})(typeof global !== 'undefined' ? global : this);
```
Comment (fearphage) [inline lib/sinon/util/fake_xml_http_request.js]: @cjohansen The build is failing on master because there are single quotes here instead of the jscs required double quotes.

Comment (jmeas) [inline lib/sinon/util/fake_xml_http_request.js]: lol oops : [  :speak_no_evil:

Comment (jmeas) [inline lib/sinon/util/fake_xml_http_request.js]: I think it's failing already due to #660, but I'll go ahead and open a PR to correct this.

Comment (cjohansen) [inline lib/sinon/util/fake_xml_http_request.js]: Thanks for discovering and fixing!
